_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 29
                - 41
                - 55
                - 105
            "2":
                - 1
                - 29
                - 41
                - 55
                - 105
            "3":
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
